### PR TITLE
Finished building my Main Blog Page

### PR DESCRIPTION
**Pull request by Illustre13**
#### What does this PR do?

This PR contains the progress I have made on My Brand Project, where I have finished building the design of the main blog page.

#### Description of Task to be completed

In this PR I have completed  the design of these following features:
    ➡ Built Blog Front Page
    ➡ Built Blog Hot Topics Section
    ➡ Built Blog Editors pick Section
    ➡ Built Blog Recent Post Section
    ➡ Built Blog Side Popular Post Section and
    ➡ Built Blog Side Recent Comment Section

#### How should this be manually tested?
You can Check my the progress via Netlify https://ith-mybrand.netlify.app/index.html
#### What are the relevant pivotal tracker stories?

The Trello Card for this PR is can be seen here

➡https://trello.com/c/0DnZuD8W

#### Screenshots (if appropriate)
```

### CODE REVIEW

**Comment by Illustre13** [comment]
[Finished Building The Main Blog Page](https://trello.com/c/0DnZuD8W/14-1-finished-with-nav-bar-the-front-page-about-me-page-timeline-page-my-skills-page-my-portfolio-page-and-the-contact-page)

**Comment by Illustre13** [comment]
[Finished Building The Main Blog Page](https://trello.com/c/0DnZuD8W/14-1-finished-with-nav-bar-the-front-page-about-me-page-timeline-page-my-skills-page-my-portfolio-page-and-the-contact-page)

**Comment by Illustre13** [comment]
[Finished Building The Main Blog Page](https://trello.com/c/0DnZuD8W/14-1-finished-with-nav-bar-the-front-page-about-me-page-timeline-page-my-skills-page-my-portfolio-page-and-the-contact-page)

**Comment by Illustre13** [comment]
[Finished Building The Main Blog Page](https://trello.com/c/0DnZuD8W/14-1-finished-with-nav-bar-the-front-page-about-me-page-timeline-page-my-skills-page-my-portfolio-page-and-the-contact-page)

**Comment by Illustre13** [comment]
[Finished Building The Main Blog Page](https://trello.com/c/0DnZuD8W/14-1-finished-with-nav-bar-the-front-page-about-me-page-timeline-page-my-skills-page-my-portfolio-page-and-the-contact-page)

**Comment by Illustre13** [comment]
[Finished building my Main Blog Page](https://trello.com/c/0DnZuD8W/14-finished-building-my-main-blog-page)

**Review by chrisostome01 — APPROVED** [review]
# Great job

**Pull request merged**
